class EnData {
  List<String> endata = [
    'Myanmar Economic Policies',
    'Investment Policies',
    'Myanmar Investment Law',
    'Myanmar Investment Rule',
    'MIC Services Fees',
    'Notification No. (49/2014)',
    'Notification No. (50/2014)',
    'Notification No. (51/2014)',
    'Notification No. (10/2017)',
    'Notification No. (11/2017)',
    'Notification No. (13/2017)',
    'Notification No. (15/2017)',
    'Notification No. (84/2017)',
    'Notification No. (85/2017)',
    'Notification No. (86/2017)',
    'Notification No. (87/2017)',
    'Announcement of Myanmar Investment Commission - Invitation to invest in Import Substitute Commodities',
    'Notification No. (5/2018)',
    'Notification No. (7/2018)',
    'Form (1)',
    'Form (2)',
    'Form (3)',
    'Form (4-A)',
    'Form (4-B)',
    'Form (5-A)',
    'Form (5-B)',
    'Form (6)',
    'Form (7-A)',
    'Form (7-B)',
    'Form (8)',
    'Form (9)',
    'Form (10)',
    'Form (11)',
    'Form (12-A)',
    'Form (12-B)',
    'Form (13)',
    'Form (14)',
    'Announcement of Myanmar Investment Commission - Invitation to invest in Logistics Services',
    'Appointment of foreign experts',
    'Myanmar Company Law',
    'Myanmar Companies Regulations',
    'Company Director Guide',
    'Myanmar Economic Zone Law',
    'Special Economic Zone Rule',
    'Constitution of the Republic of the Union of Myanmar',
    'OECD Benchmark Definition of FDI (4th Edition 2008)',
    'Balance of Payment and International Investment Position Manual 6th Edition)',
    'Myanmar Investment Promotion Plan - MIPP',
    'ISIC Code',
    'CPC Code',
    'MDCV',
    'ACIA',
    'Protocol to Amend the ACIA',
    'PSD Framework and Action Plan',
    'Cost of Doing Business Survey Report',
    'PPP Framework',
    'Policy Framework for Investment - PFI (2015 Edition)',
    'SDG Goals (2016)',
    'WTO (Legal Texts)',
    'OECD Investment Policy Review',
    'The Export and Import Law',
    'Investment Policy Framework',
    'International Practices Policy Framework of Investing Across Border',
    'Aftercare Services International Practices of FDI',
    'Role of Investment Promotion Agency',
    'Framework for FDI promotion Framework for FDI promotion',
    'Inf Consolidated Text for Investment Facilities in WTO',
    'Investment Application Guidebook',
    'Multilateral Trading System and Foreign Multilateral Trading System and Foreign Direct Investment and FDIS Compilation',
    'Myanmar Systainable Development Plan',
    'The ASEAN Charter',
    'ASEAN Economic Community Blueprint 2025',
    'Notification No. (2/2018) Project Bank Notification',
    'COVID-19 Economic Relief Plan(CERP)'
  ];

  List<String> pdflink = [
    'assets/pdf/en/en01.pdf',
    'assets/pdf/en/en02.pdf',
    'assets/pdf/en/en03.pdf',
    'assets/pdf/en/en04.pdf',
    'assets/pdf/en/en05.pdf',
    'assets/pdf/en/en06.pdf',
    'assets/pdf/en/en07.pdf',
    'assets/pdf/en/en08.pdf',
    'assets/pdf/en/en09.pdf',
    'assets/pdf/en/en10.pdf',
    'assets/pdf/en/en11.pdf',
    'assets/pdf/en/en12.pdf',
    'assets/pdf/en/en13.pdf',
    'assets/pdf/en/en14.pdf',
    'assets/pdf/en/en15.pdf',
    'assets/pdf/en/en16.pdf',
    'assets/pdf/en/en17.pdf',
    'assets/pdf/en/en18.pdf',
    'assets/pdf/en/en19.pdf',
    'assets/pdf/en/en20.pdf',
    'assets/pdf/en/en21.pdf',
    'assets/pdf/en/en22.pdf',
    'assets/pdf/en/en23.pdf',
    'assets/pdf/en/en24.pdf',
    'assets/pdf/en/en25.pdf',
    'assets/pdf/en/en26.pdf',
    'assets/pdf/en/en27.pdf',
    'assets/pdf/en/en28.pdf',
    'assets/pdf/en/en29.pdf',
    'assets/pdf/en/en30.pdf',
    'assets/pdf/en/en31.pdf',
    'assets/pdf/en/en32.pdf',
    'assets/pdf/en/en33.pdf',
    'assets/pdf/en/en34.pdf',
    'assets/pdf/en/en35.pdf',
    'assets/pdf/en/en36.pdf',
    'assets/pdf/en/en37.pdf',
    'assets/pdf/en/en38.pdf',
    'assets/pdf/en/en39.pdf',
    'assets/pdf/en/en40.pdf',
    'assets/pdf/en/en41.pdf',
    'assets/pdf/en/en42.pdf',
    'assets/pdf/en/en43.pdf',
    'assets/pdf/en/en44.pdf',
    'assets/pdf/en/en45.pdf',
    'assets/pdf/en/en46.pdf',
    'assets/pdf/en/en47.pdf',
    'assets/pdf/en/en48.pdf',
    'assets/pdf/en/en49.pdf',
    'assets/pdf/en/en50.pdf',
    'assets/pdf/en/en51.pdf',
    'assets/pdf/en/en52.pdf',
    'assets/pdf/en/en53.pdf',
    'assets/pdf/en/en54.pdf',
    'assets/pdf/en/en55.pdf',
    'assets/pdf/en/en56.pdf',
    'assets/pdf/en/en57.pdf',
    'assets/pdf/en/en58.pdf',
    'assets/pdf/en/en59.pdf',
    'assets/pdf/en/en60.pdf',
    'assets/pdf/en/en61.pdf',
    'assets/pdf/en/en62.pdf',
    'assets/pdf/en/en63.pdf',
    'assets/pdf/en/en64.pdf',
    'assets/pdf/en/en65.pdf',
    'assets/pdf/en/en66.pdf',
    'assets/pdf/en/en67.pdf',
    'assets/pdf/en/en68.pdf',
    'assets/pdf/en/en69.pdf',
    'assets/pdf/en/en70.pdf',
    'assets/pdf/en/en71.pdf',
    'assets/pdf/en/en72.pdf',
    'assets/pdf/en/en73.pdf',
    'assets/pdf/en/en74.pdf',
  ];
}
